version: '3.7'
services:

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=talktome
      - POSTGRES_DB=worldpopulation

    ports:
      - "5432:5432"

    volumes:
      - /data/populationdb:/var/lib/postgres/data
      - /data/populationdb/population.sql:/docker-entrypoint-initdb.d/population.sql
